name: github-actions-typescript-template
description: GitHub Actions TypeScript template
author: remarkablemark
inputs:
  version:
    description: Description
    required: false
    default: Default
runs:
  using: node16
  main: dist/index.js
