name: github-actions-typescript-template
description: GitHub Actions TypeScript Template
author: remarkablemark
inputs:
  version:
    description: Description
    default: 1.2.3
runs:
  using: node20
  main: dist/index.js
branding:
  icon: activity
  color: white
